/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7-dev */

#ifndef PB_LOCATION_PB_H_INCLUDED
#define PB_LOCATION_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _LocationMessage { 
    pb_callback_t aware_device_id;
    bool has_message_id;
    uint32_t message_id;
    bool has_sequence_number;
    uint32_t sequence_number;
    bool has_retry_number;
    uint32_t retry_number;
    bool has_timestamp;
    uint64_t timestamp;
    bool has_time_offset_fix;
    uint64_t time_offset_fix;
    pb_callback_t location_type;
    bool has_latitude;
    double latitude;
    bool has_longitude;
    double longitude;
    bool has_altitude;
    double altitude;
    bool has_als;
    float als;  
    bool has_temperature;
    float temperature;
    bool has_pressure;
    float pressure;
    bool has_humidity;
    float humidity;
} LocationMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define LocationMessage_init_default             {{{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define LocationMessage_init_zero                {{{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define LocationMessage_aware_device_id_tag      1
#define LocationMessage_message_id_tag           2
#define LocationMessage_sequence_number_tag      3
#define LocationMessage_retry_number_tag         4
#define LocationMessage_timestamp_tag            5
#define LocationMessage_time_offset_fix_tag      6
#define LocationMessage_location_type_tag        7
#define LocationMessage_latitude_tag             8
#define LocationMessage_longitude_tag            9
#define LocationMessage_altitude_tag             10
#define LocationMessage_temperature_tag          11
#define LocationMessage_pressure_tag             12
#define LocationMessage_humidity_tag             13

/* Struct field encoding specification for nanopb */
#define LocationMessage_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   aware_device_id,   1) \
X(a, STATIC,   OPTIONAL, UINT32,   message_id,        2) \
X(a, STATIC,   OPTIONAL, UINT32,   sequence_number,   3) \
X(a, STATIC,   OPTIONAL, UINT32,   retry_number,      4) \
X(a, STATIC,   OPTIONAL, UINT64,   timestamp,         5) \
X(a, STATIC,   OPTIONAL, UINT64,   time_offset_fix,   6) \
X(a, CALLBACK, OPTIONAL, STRING,   location_type,     7) \
X(a, STATIC,   OPTIONAL, DOUBLE,   latitude,          8) \
X(a, STATIC,   OPTIONAL, DOUBLE,   longitude,         9) \
X(a, STATIC,   OPTIONAL, DOUBLE,   altitude,         10) \
X(a, STATIC,   OPTIONAL, FLOAT,    temperature,      11) \
X(a, STATIC,   OPTIONAL, FLOAT,    pressure,         12) \
X(a, STATIC,   OPTIONAL, FLOAT,    humidity,         13)
#define LocationMessage_CALLBACK pb_default_field_callback
#define LocationMessage_DEFAULT NULL

extern const pb_msgdesc_t LocationMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define LocationMessage_fields &LocationMessage_msg

/* Maximum encoded size of messages (where known) */
/* LocationMessage_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
